# Permalinks
permalink:           "/blog/:title"
excerpt_separator:   <!--more-->
# Setup
title:               GulaAren
tagline:             GulaAren blog
url:                 "https://GulaAren.github.io"
paginate:            7
paginate_path:       "/blog/:num/"
baseurl:             ""
highlighter:         rouge
exclude:
- post.bak
- CNAME
- README.md

collections:
  labels:
    permalink: "/:collections/:path"
    output: true
  categories:
    permalink: "/:collections/:path"
    output: true

kramdown:
   math_engine: mathjax
   syntax_highlighter: rouge

sass:
  style:             compressed

plugins:
  - jekyll-paginate

# About/contact
author:
  name:              GulaAren
  url:               https://GulaAren.github.io
  email:             ""

github:
  repo:              https://github.com/GulaAren

#analytics_id:        ""

