# Permalinks
permalink:           "/blog/:title/"
excerpt_separator:   <!--more-->
# Setup
title:               TesManis
tagline:             TesManis Blog
url:                 "https://tesmanis.github.io"
paginate:            7
paginate_path:       "/blog/:num/"
baseurl:             ""
highlighter:         rouge
kramdown:
   math_engine: mathjax
   syntax_highlighter: rouge

sass:
  style:             compressed

plugins:
  - jekyll-paginate

# About/contact
author:
  name:              Tes Manis
  url:               https://tesmanis.github.io
  email:             ""

github:
  repo:              https://github.com/TesManis

#analytics_id:        ""

